export default function Head() {
  return (
    <>
      <title>Steven Ho Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create enxt app" />
      <link rel="icon" href="favicon.ico" />
    </>
  );
}